cloudfoundry/docs-dev-guide

- installcf/develop-cli-plugins.html.md
- installcf/index.html.md
Link to cf CLI plugin [development guide](https://github.com/cloudfoundry/cli/tree/master/plugin_examples)
> link to cli plugin development guide

- deploy-apps/manifest.html.md.erb
[#84814280]
Signed-off-by: Jonathan Berkhahn <jaberkha@us.ibm.com>
> Document the use of hosts in manifest

- deploy-apps/manifest.html.md.erb
Signed-off-by: Simon Leung <leungs@us.ibm.com>
> fix error in manifest - hosts section

- deploy-apps/environment-variable.html.md
Updated the environment variables output as per the 
https://www.pivotaltracker.com/story/show/88539012
> Updating environment variables output of 'cf env my-app'

- deploy-apps/manifest.html.md.erb
This PR resolves  https://www.pivotaltracker.com/story/show/90558428
> Documenting --no-hostname attribute in app manifest.yml

- deploy-apps/manifest.html.md.erb
Updating the ```disk_quota``` attribute in the manifest docs
> Updating docs with `disk_quota` attribute

- installcf/whats-new-v6.html.md.erb
* ja_JA -> ja_JP as of cli d90b07b (Use ja_JP instead of ja_JA)
Signed-off-by: Muhammad Altaf <malik.altaf@gmail.com>
> Update supported languages

- deploy-apps/manifest.html.md.erb
- deploy-apps/prepare-to-deploy.html.md.erb
Add documentation about capturing sigterm call to stop apps and
how to construct appropriate start commands.
[#111391006]
Signed-off-by: Amelia Downs <adowns@pivotal.io>
> Add documentation about apps stoping and start commands

- deploy-apps/routes-domains.html.md.erb
Updated dev docs for routes with a path
- Added new section for creating routes with a path
- Update list routes to include path
- Add new section for check route
- Update examples for map, unmap and delete route to include path support
See: https://www.pivotaltracker.com/story/show/106034096
cc @shalako
> Update docs for Routes with a Path

- services/index.html.md.erb
- services/route-binding.html.md.erb
- services/user-provided.html.md.erb
The following PR to dev docs includes updates to for new Route Services feature.
- New top level section in "Services" for Route services
- new page for "Managing Application Requests with Route Services"
- updates to user provided services for route services
Cheers
@markstgodard @fordaz @shalako
CF Routing Team
> Dev doc updates for Route Services

- deploy-apps/trusted-system-certificates.html.md.erb
Feel free to edit or move this.  It is initial documentation for the Diego feature not yet released. [#113241421]
Signed-off-by: Amelia Downs <adowns@pivotal.io>
Here is the link to our tracker story ...
https://www.pivotaltracker.com/story/show/113241421
Thanks!
> Trusted System Certificates documentation from Diego

- deploy-apps/ssh-apps.html.md.erb
@adowns01
Signed-off-by: Amelia Downs <adowns@pivotal.io>
> Add docs about SSH environment

- deploy-apps/ssh-apps.html.md.erb
* Extract environmental setup into its own section
* Clarify instructions for `.profile.d` scripts
* Change working directory in addition to environment
* Add additional information about VCAP_APPLICATION differences
[#115355041]
> Revise SSH environment commands

- deploy-apps/index.html.md.erb
- deploy-apps/trusted-system-certificates.html.md.erb
- index.html.md.erb
* Add to Dev Guide and Application Deployment tables of contents
[#112556023]
[#113241421]
> Revise trusted system certificates page

- deploy-apps/deploy-app.html.md.erb
- deploy-apps/index.html.md.erb
- deploy-apps/prepare-to-deploy.html.md.erb
- deploy-apps/routes-domains.html.md.erb
- deploy-apps/streaming-logs.html.md.erb
- deploy-apps/troubleshoot-app-health.html.md.erb
- services/log-management-thirdparty-svc.html.md.erb
- services/migrate-db.html.md.erb
Spaces, it is aligned to view code with any editor, including the web page view (such as in the GitHub code). When use tabs, the view on the page is chaos, and it is terrible to mix tabs and spaces.
> Replace the tab with spaces

- deploy-apps/manifest.html.md.erb
Merge this pull request to bring commits into the 1.8 branch.
> Master to 1.8

- deploy-apps/deploy-app.html.md.erb
- This ensures that users/readers are aware that credentials can potentially be leaked by this issue.
[#128244503]
Signed-off-by: Gabriel Ramirez <gabriel.e.ramirez@gmail.com>
> Add clarification on .profile in PHP note about credential leakage

- deploy-apps/manifest.html.md.erb
- services/migrate-db.html.md.erb
Full width turn half-width character
> “ should be "

- deploy-apps/routes-domains.html.md.erb
Hi, 
This PR adds documentation for routing requests based on app instance ID and index.
Regards
Shash && Edwin
> Add documentation for surgical routing

- deploy-apps/manifest.html.md.erb
- Related to cloudfoundry/ruby-buildpack#69
[#134258225]
> Add note about manifest env vars in staging container

- deploy-apps/environment-variable.html.md.erb
> add documentation for `CF_INSTANCE_INTERNAL_IP`

- using-tasks.html.md.erb
addresses https://github.com/cloudfoundry/cli/issues/1034
> added to workflow how to inspect the logs of a submitted task

- deploy-apps/environment-variable.html.md.erb
[#136783989]
Signed-off-by: Dave Goddard <dave@goddard.id.au>
Signed-off-by: Sam Smith <sesmith177@gmail.com>
> Add DATABASE_URL to list of provided CF ENV Variables

- deploy-apps/environment-variable.html.md.erb
Signed-off-by: Mike Lloyd <mlloyd@pivotal.io>
> fixed typo.

- deploy-apps/manifest.html.md.erb
Support for this attribute was added in cf CLI 6.24.0.
> added health-check-http-endpoint

- deploy-apps/blue-green.html.md.erb
> Reword blue-green as deployment technique, not release

- services/using-vol-services.html.md.erb
- [#141981411](https://www.pivotaltracker.com/story/show/141981411)
> Add missing documentations on Mount path for Volume Services

- services/log-management-thirdparty-svc.html.md.erb
Updated the docs to include the TLS option
> Update to include TLS

- deploy-apps/routes-domains.html.md.erb
The word "they" is used but missing the letter "y". This adds that letter.
> Add missing 'y'

- deploy-apps/streaming-logs.html.md.erb
> Fixes spelling in streaming-logs section.

- deploy-apps/streaming-logs.html.md.erb
The channels are OUT and ERR, not STDOUT and STDERR
> Clarify the "channel" names

- deploy-apps/troubleshoot-app-health.html.md.erb
> the descriptions of these env vars were moved into push

- deploy-apps/manifest.html.md.erb
- these attributes include `docker.image` and `docker.username`
> add documentation for specifying Docker attributes

- deploy-apps/manifest.html.md.erb
Mistyping - two subsequent 'when'
> Mistyping - two subsequent 'when'

- deploy-apps/instance-identity.html.md.erb
- index.html.md.erb
[#154001954](https://www.pivotaltracker.com/story/show/154001954)
**Note:** There is a related PR for enabling the Instance Identity system: https://github.com/cloudfoundry/docs-cf-admin/pull/112
> Document using Instance Identity system

- services/application-binding.html.md.erb
Tracker story here: https://www.pivotaltracker.com/story/show/143843317
Please do not merge until approved by @zrob
> Add docs for named service bindings

- deploy-apps/instance-identity.html.md.erb
[#154533193]
Signed-off-by: Nima Kaviani <nkavian@us.ibm.com>
> update docs to reflect instance identity OU update with org/space guid

- deploy-apps/instance-identity.html.md.erb
- Minor edits for clarity and consistency with operator configuration document.
Related: https://github.com/cloudfoundry/docs-cf-admin/pull/118
[#157321019]
> Edit instance identity usage document

- deploy-apps/manifest.html.md.erb
Please do not merge this in yet. Thanks.
> Add Variable Substitution Feature to Manifest Doc [#157270890]

- deploy-apps/manifest.html.md.erb
Fixes issues with formatting here: https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#multi-manifests
> Fixes Manifest Output Display

- deploy-apps/manifest.html.md.erb
Please merge when you can, thank you.
> Improve Example for Partial Values

- v3-commands.html.md.erb
[#138101297](https://www.pivotaltracker.com/story/show/138101297)
> add new v3 commands

- deploy-apps/cf-networking.html.md.erb
- deploy-apps/routes-domains.html.md.erb
[#159503990]
Signed-off-by: Aidan Obley <aobley@pivotal.io>
> update language around service discovery for GA

- deploy-apps/healthchecks.html.md.erb
Hi there, please do not pull this in yet. Thank you.
> Add V3 Command HTTP Invocation Text For App Health

- deploy-apps/troubleshoot-app-health.html.md.erb
Please do not merge this yet, thanks.
> Update CF Events: Crashed Event With Diego Cell & Instance Guid

- services/_using-vol-services.html.md.erb
[#159441838](https://www.pivotaltracker.com/story/show/159441838)
Please let us know if you have any questions.
@mariash and Dave
> Remove obsolete NFS mount warnings

- services/_using-vol-services.html.md.erb
Hi docs,
We would like to submit this PR for your consideration.  Please let us have your comments and we'll make the necessary edits.
Persi team
> Add NFS Volume Service docs

- services/_using-vol-services.html.md.erb
> Document nfs-experimental service performance improvements

- services/sharing-instances.html.md.erb
The service instance sharing feature is now Generally Available!
> Service instance sharing is now GA

- services/_using-vol-services.html.md.erb
[#159050331](https://www.pivotaltracker.com/story/show/159050331)
Let us know if you have any questions.
@mariash and Dave
> Clarify references to nfs-experimental as a separate service, not a plan

- capi/client-libraries.html.md.erb
> Reference python CC API clients

- deploy-apps/ssh-apps.html.md.erb
Refine scp command example to cover the example of local file to app destination
> Refine scp command example

- services/_using-vol-services.html.md.erb
Not supported in 283
[#160597290](https://www.pivotaltracker.com/story/show/160597290)
> Remove "version" parameter reference

- services/_using-vol-services.html.md.erb
* Default value
* Valid values
[#160597290](https://www.pivotaltracker.com/story/show/160597290)
> Clarify "version" parameter in volume services

- deploy-apps/routes-domains.html.md.erb
> Update internal domain, service discovery section

- deploy-apps/ssh-apps.html.md.erb
> Clarify scp command

- deploy-apps/push-docker.html.md.erb
We had someone not find this and complain about it.
> Add note about start command

- deploy-apps/blue-green.html.md.erb
Reverts cloudfoundry/docs-dev-guide#328
> Revert "Remove unmaintained Autopilot from impl. section"

- services/_using-vol-services.html.md.erb
Hi Docs Team,
This PR updates the NFS volume service docs to reflect a recent change we made to auto-negotiate the NFS protocol version by default. See [#164095794](https://www.pivotaltracker.com/story/show/164095794) for more details.
Let us know if you have any questions.
Thanks,
Paul and @davewalter 
cc @julian-hj
> Update NFS volume service doc to reflect protocol auto-negotiation

- custom-ports.html.md.erb
> Fix custom port command syntax examples

- weighted-routing.html.md.erb
Added blue-green deploys as a usecase
> blue-green deploys as a usecase

- deploy-apps/manifest-attributes.html.md.erb
[finishes #164237899](https://www.pivotaltracker.com/story/show/164237899)
> Add note clarifying environment variable rules

- sidecars.html.md.erb
[#166915511](https://www.pivotaltracker.com/story/show/166915511)
Co-authored-by: Sannidhi Jalukar <sjalukar@pivotal.io>
Co-authored-by: Chris Selzo <cselzo@pivotal.io>
> Add sidecar documentation for java apps

- services/_using-vol-services.html.md.erb
[#167579635](https://www.pivotaltracker.com/story/show/167579635)
Signed-off-by: Paul Warren <paul.warren@emc.com>
Co-authored-by: Paul Warren <paul.warren@emc.com>
cc/@julian-hj @DennisDenuto
> document the limitation that 'uid' & 'gid' must be positive integer values

- deploy-apps/push-docker.html.md.erb
> Update documentation around pushing images from AWS ECR to CF

- deploy-apps/streaming-logs.html.md.erb
updating the docs to include references to the new app log rate limit feature.
more context can be found here: https://www.pivotaltracker.com/story/show/170092847
> Add log rate limit desc/example for CELL

- deploy-apps/routes-domains.html.md.erb
Add clarifying detail around errors and header values provided when a request fails
[#171304381](https://www.pivotaltracker.com/story/show/171304381)
> Update Surgical Routing Docs

- deploy-apps/environment-variable.html.md.erb
changing "To see the value of the VCAP\_SERVICES environment variable" to "To see the value of the VCAP_SERVICES environment variable
> Updating typo

- deploy-apps/manifest-attributes.html.md.erb
[#170293332]
Co-authored-by: Belinda Liu <bliu@pivotal.io>
> Add manifest schema version to manifest attributes docs

- deploy-apps/manifest-attributes.html.md.erb
Fix https://github.com/cloudfoundry/docs-dev-guide/issues/303
> Add manifest documentation for instances

- services/index.html.md.erb
To match with the correct documentation here https://docs.cloudfoundry.org/devguide/using-tasks.html#run-tasks-v7
> Fix example

- services/sharing-instances.html.md.erb
[#163941956](https://www.pivotaltracker.com/story/show/163941956)
> Add docs for viewing sharing status for service instances

- deploy-apps/app-lifecycle.html.md.erb
* We weren't sure how to reference the IST tile properly. Maybe there is a variable for it? 
* This info is valid for all supported versions of TAS. Can you please cherry-pick to the appropriate branches? 
Thank you!
@ameowlia and @benjamintf1
> update graceful shutdown info

- multiple-processes.html.md.erb
* also remove references to v6 CLI
> Add instructions for pushing multi-process apps with manifests

- services/log-management.html.md.erb
We updated the version of capi referenced to the one that also has ca's. 
Signed-off-by: Carson Long <lcarson@vmware.com>
> add ca to mtls drain information

- deploy-apps/healthchecks.html.md.erb
- deploy-apps/manifest-attributes.html.md.erb
Update the health checks and manifest attributes documentation for the upcoming in 5.0 "Application readiness health checks" feature.
> [DRAFT] Document new app readiness health checks

- services/log-management.html.md.erb
- services/metrics.html.md.erb
@chombium, I made some updates based on your conversation with @myeghiazarya in June. I thought it would be easier to get these additions done if I started them -- gives you a target to shoot at. 
@myeghiazarya, I will be happy to see your input, too, since you tried this stuff out right away.
When we are done with this, then I will update the Loggregator architecture page and add the new page I made to the CF book, but I thought we could start here.
@chombium, I tried to add you as an official reviewer, but I wasn't able to. I don't want to merge this update until you have checked it. Thanks :)
> add missing metrics details

- deploy-apps/environment-variable.html.md.erb
> Minor change to environment-variable.html.md.erb

- deploy-apps/manifest.html.md.erb
* copied from v3 apidoc: https://v3-apidocs.cloudfoundry.org/version/3.169.0/index.html#apply-a-manifest-to-a-space
> Add explanation that manifest config does not change existing resources

- deploy-apps/streaming-logs.html.md.erb
This change should go into:
- TAS 4/5/6/7
> Add app log revision information

- sidecars.html.md.erb
Adds a tutorial for an additional sidecar use case.
> Add example debug sidecar use case

- custom-per-route-options.html.md.erb
- deploy-apps/manifest-attributes.html.md.erb
- routing-index.html.md.erb
The PR provides documentation on how to use the newly implemented per-route load balancing algorithm feature.
> feat: document usage of per-route features

- custom-per-route-options.html.md.erb
Add version information from which this feature is available (via variable in docs-book-cloudfoundry).
See https://github.com/cloudfoundry/docs-book-cloudfoundry/pull/149 for the variable
> docs(per-route-lb): add version information

- deploy-apps/_c2c_oss_overlay.html.md.erb
Draft because this work is not merged in yet. Longer description of this work is here: cloudfoundry/silk-release#148
This change is ONLY for OSS.
> update oss c2c-overlay guide

- revisions.html.md.erb
Include revision and rollback command instructions.
> Add revision command info

- deploy-apps/environment-variable.html.md.erb
- deploy-apps/large-app-deploy.html.md.erb
- deploy-apps/manifest-attributes.html.md.erb
- services/_using-vol-services.html.md.erb
- services/application-binding.html.md.erb
- services/managing-services.html.md.erb
- services/user-provided.html.md.erb
Add documentation about file-based service bindings: https://github.com/cloudfoundry/community/issues/901
> Add file-based service binding information to dev docs

- deploy-apps/user-rate-limits.html.md.erb
> TNZ-61476 - Remove CAPI Changes from rate limits by user documentation
