deploy-apps/prepare-to-deploy.html.md.erb
According to the latest cf cli source and its behavior,
- .hg and .DS_Store are also ignored files
- .darc should be _darc
=> Update ignore description

deploy-apps/manifest.html.md.erb
Replaced 'subdomain' attribute used in manifest examples to 'host'.
Issue : https://github.com/cloudfoundry/docs-dev-guide/issues/34
=> Changes in attribute used in the manifest.

services/adding-a-service.html.md
This section probably doesn't apply to most services, so it might confuse users to include it with such a general-sounding title. We made a github issue about this section in case the information would be valuable elsewhere.
https://github.com/cloudfoundry/docs-dev-guide/issues/42
=> Remove "Choosing the Right Plan" section from create-service docs

services/managing-services.html.md.erb
The Table of Contents wants a unique anchor for each section, so you can properly navigate the page.
[#94895060]
=> Fixed uniqueness for anchor link

deploy-apps/environment-variable.html.md.erb
* Combine app-specific and instance-specific sections
* Remove some explicit references to DEAs
* Update VCAP_APPLICATION fields and descriptions
* Add notes on variables and fields not provided on Diego backend
* Clarify behavior of `PORT` variable
=> Revise environment variable descriptions

installcf/install-go-cli.html.md.erb
Since cf CLI v6.14.1 (released 23 Dec 2015) we digitally sign the Mac OS X installer so this warning no longer appears.
=> this security warning no longer appears

services/user-provided.html.md.erb
I noticed my changes to https://github.com/cloudfoundry/docs-dev-guide/blob/master/services/user-provided.html.md.erb were reverted with other contributions in this commit:
https://github.com/cloudfoundry/docs-dev-guide/commit/483a83295f3dff8a355dc63ffc27453cd9de5060?diff=unified
My changes to route-domains.html appear to have been put back in
https://github.com/cloudfoundry/docs-dev-guide/commit/5e699f9ca66701e36bb87d522e65840b07f85a8e
But the changes to user-provided.html didn't come along.
=> changes that were reverted and never made it in

deploy-apps/routes-domains.html.md.erb
Docs was not describing restrictions on admins for wildcard routes
=> Wildcard routes on shared domains restricted to admins

services/log-management-thirdparty-svc.html.md.erb
[Logit](https://logit.io) is a hosted ELK service and is compatible with Cloud Foundry log drains.
cc @mrdavidlaing
=> Add logit-io log drain documentation

deploy-apps/manifest.html.md.erb
We added an additional section in [here](https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html) to describe a newly released feature that allows application routes in the app manifest.
Story in the CF-CLI tracker [#121917921](https://www.pivotaltracker.com/story/show/121917921)
=> add routes attribute to app manifest deployment

services/log-management-thirdparty-svc.html.md.erb
Some of the examples include the `cf bind` step, so I added that where it was missing.
=> Don't skip bind step for the clueless (like me...)

deploy-apps/deploy-app.html.md.erb
- PHP Buildpack will not execute .profile scripts
- PHP apps staged with the buildpack will host the .profile script
[#128244503]
Signed-off-by: James Wen <jrw2175@columbia.edu>
=> Add warning about .profile issues in PHP Buildpack

deploy-apps/environment-variable.html.md.erb
The example VCAP_APPLICATION's application_uris and uris arrays should be the same, as described.
=> Fix typo in VCAP_APPLICATION example

services/route-binding.html.md.erb
The sample output was un-parameterized & references an unused domain (myapp.superman.cfapps.io) and the wrong service (myspringlogger)
=> Sample output references wrong domain

services/route-binding.html.md.erb
Reverts cloudfoundry/docs-dev-guide#139
=> Revert "Sample output references wrong domain"

deploy-apps/app-ssh-overview.html.md.erb, deploy-apps/ssh-apps.html.md.erb
The current description of the roles in these docs don't match the names
of the roles that are set within CF. `cf space-users` returns "SPACE
MANAGER", "SPACE DEVELOPER" and "SPACE AUDITOR".
This updates the docs to use these names, which should make things
clearer.
=> Clarify roles in SSH docs.

README.md, capi/client-libraries.html.md.erb
Related to cloudfoundry/api-docs#3
=> Add client library list for the CAPI API

deploy-apps/ssh-apps.html.md.erb
`source` only takes a single file argument, meaning if there is more than one file returned by the shell glob it will be ignored and not sourced. There are shorter versions of the fixed command, but they are shell specific whereas this is portable across shells.
=> Fix ssh environment `source` command example

deploy-apps/ssh-apps.html.md.erb
This would cause a harmless error when used in environments built using buildpacks that do not create a `.profile.d`.
Given the error worries users it is better to be defensive up front and silently do nothing.
=> Fix ssh env sourcing in environments without a .profile.d

deploy-apps/ssh-services.html.md.erb
We conducted some usability testing with the scenario of having people try to import data into a postgres database by following the Accessing Services with SSH guide.
We found two things that slowed people down:
There are quite a few things we noticed that people spent time on here, copying and pasting hostnames, database names and credentials out of JSON for example, although I haven't addressed that. The thing I chose to address here was that they weren't able to see what to substitute for `spring-music` without reading further on in the docs. 
People don't read on in the docs, they prefer to finish each step before they move forward, so it doesn't matter if you give them the answer on the following line; they probably won't read it. 
That `-N` flag in `cf ssh` threw everyone for at …
=> Usability improvements to accessing services via SSH

deploy-apps/environment-variable.html.md.erb
The Cloud Foundry Environment Variables section has three tables. In the first table—VCAP_APPLICATION—every sentence/sentence fragment ends with a period. In the second table—VCAP_SERVICES—periods are used inconsistently (only one fragment out of five ends with a period). The third table—Environment Variable Groups—doesn’t have any ending punctuation marks.
To make the punctuation consistent, I added periods to every sentence fragment in the second and third tables.
=> Make punctuation in tables consistent

deploy-apps/ssh-apps.html.md.erb
There is no '-tt'. Also, `-T` is to disable pseudo-tty allocation, so does not belong in a list of flags to "let you run an SSH session in pseudo-tty".
http://cli.cloudfoundry.org/en-US/cf/ssh.html
=> removed unsupported flag

deploy-apps/manifest.html.md.erb
If omitting quotes, cli fails with following message:
``Error reading manifest file:
yaml: line 30: did not find expected alphabetic or numeric character
``
/CC @dkoper
=> Clarifies CLI manifest syntax for wildcard hosts

deploy-apps/environment-variable.html.md.erb
Please don't merge until @zrob gives the thumbs-up.
---
Hello Docs Team,
Due to some confusion regarding which environment variables are used where, we've created a table to highlight which environment variables are necessary at different parts of the app lifecycle.
We've also clarified the usage of `LANG`, which caused some confusion in [this issue](https://github.com/cloudfoundry/nodejs-buildpack/issues/83). 
Finally, we've removed some instances of "when running on Diego" since DEAs are no longer supported and we can assume the user will be running the apps on Diego.
[**Tracker Story: #145463555**](https://www.pivotaltracker.com/story/show/145463555) 
---
- Added a table to distinguish which environment variables are used for staging,
running, and tasks
- Added a description for the …
=> Add table for env vars; describe `LANG`

deploy-apps/manifest.html.md.erb
Application health check type `none` is deprecated in favor of `process`
=> update health check type

deploy-apps/stopping-and-deleting-apps.md
The commands related to stopping and deleting apps are simple, but we want to convey the consequences and things to consider when doing so. This will allow Cloud Foundry users to keep their orgs and spaces tidy, and avoid errors, such as routes already existing because they were initially created in another space and were never deleted.
This was written for [the tech docs](https://docs.cloud.service.gov.uk/#stopping-and-deleting-apps) of our implementation of open source Cloud Foundry. It has been edited to remove our own perspective and terminology, but it could do with a read through to check it makes sense in the new context.
Also, this is my first time writing in the particular brand of markdown/HTML you like to use, so you may want to polish it more inline with your conventions.
=> Add documentation on stopping and deleting apps

deploy-apps/push-docker.html.md.erb
GCR has a bit of a different flow from the other docker registries, this
gives some information on how to push those docker images.
https://www.pivotaltracker.com/story/show/150265782
=> Add information on how to push a docker app from GCR

deploy-apps/cf-networking.html.md.erb
I left in some `<% if vars.product_name == 'PWS' %>` codes as I didn't know what they did. Please check if they still make sense.
=> replaced plugin commands with now-in-core cf CLI commands

deploy-apps/large-app-deploy.html.md.erb
used the wording from http://cli.cloudfoundry.org/en-US/cf/push.html
=> corrected `cf push -t` flag description

deploy-apps/deploy-app.html.md.erb
also reduced info a bit here so https://docs.cloudfoundry.org/devguide/deploy-apps/prepare-to-deploy.html#exclude can be the canonical text for `.cfignore`.
=> changed wording as .git etc are folders, not file extensions

deploy-apps/environment-variable.html.md.erb
https://docs.cloudfoundry.org/devguide/deploy-apps/routes-domains.html#http-vs-tcp-routes mentions 
`Applications should listen to the localhost port defined by the $PORT environment variable, which is 8080 on Diego.`
The descriptions and examples were still mentioning arbitrary dynamic ports that used to be generated DEAs.
With this PR, examples 8080 for internal ports. This allows app developers to predict internal ports, and specify them in container policies, see https://github.com/cloudfoundry/cf-networking-release/pull/24 
Also, I understand Diego does not yet support multiple app binding ports, whereas the example at https://github.com/cloudfoundry/docs-dev-guide/blob/31117ab9c3c24ddb9f4eca090d5566e70ae819d6/deploy-apps/environment-variable.html.md.erb#L264 specify more than one …
=> Clarify $PORT most often defaults to 8080 in diego

deploy-apps/ssh-apps.html.md.erb
If an app is created without ssh access enabled, you need to restart it after enabling ssh before you can actually ssh into it. Otherwise the ssh route doesn't exist and the ssh deamon is not started in the container.
This happens e.g. on landscapes where the ssh access is disabled by default for all apps ([default_app_ssh_access](http://bosh.io/jobs/cloud_controller_ng?source=github.com/cloudfoundry/cf-release&version=281#p=cc.default_app_ssh_access): false).
Related PR for cf cli: https://github.com/cloudfoundry/cli/issues/1282
=> Restart of app required after enabling SSH access

deploy-apps/manifest.html.md.erb
We initially published the app manifest deprecation changes without a reference to inheritance, because the features to replace inheritance haven't been delivered yet. Now we're thinking it would be better to state this change and invite people to provide feedback while we work on the replacement.
=> Stating that inheritance is deprecated

deploy-apps/manifest.html.md.erb
@cshollingsworth Please merge this change as a temporary solution until we have implemented an alternative to inheritance. At that point, I expect we'll remove the inheritance section from this page and mention it only with deprecated app manifest features.
=> Note for inheritance section about deprecation

deploy-apps/manifest.html.md.erb
The example of YAML anchors is invalid because it is missing a `*`. 
You can see this if you try to `cf push` the example manifest; it fails with:
```
FAILED
Error reading manifest file:
yaml: map merge requires map or sequence of maps as the value
```
=> Add missing * in YAML anchor example

deploy-apps/environment-variable.html.md.erb
This will be in CAPI release 1.46.0
[#143843207](https://www.pivotaltracker.com/story/show/143843207)
=> Add binding_name and instance_name fields to VCAP_SERVICES docs

deploy-apps/_c2c_oss_enable.html.md.erb
=> Fix upload-stemcell invocation

services/sharing-instances.html.md.erb
Add a bullet point explaining that configuration parameters used for shared service instances will be visible.
=> Configuration parameters visibility for shared service instances

v3-commands.html.md.erb
These commands no longer have the v3-prefix, so we should remove these from this doc.
cc @jbpivotal @samze
=> Remove v3-share-service and v3-share-service commands

services/sharing-instances.html.md.erb
The CLI team have removed these prefixes, so updating the docs to reflect that.
=> Remove v3 prefix from sharing commands

deploy-apps/manifest.html.md.erb
The YAML anchor/alias example wasn't quite right without these stars.
=> Include star in YAML alias example

deploy-apps/manifest.html.md.erb
`maximum_health_check_timeout` -> `health_check_timeout`
=> fix the Cloud Controller's property name

services/using-vol-services.html.md.erb
Add example of cf bind-service with LDAP user credentials as there is no client document on how to do that.
https://github.com/cloudfoundry/nfs-volume-release/blob/master/USING_LDAP.md#testing
=> add ldap bind-service example

deploy-apps/ssh-apps.html.md.erb
Add the ciphers, MACs, and key exchanges that the CF SSH proxy supports by default.
=> Add SSH proxy security configuration details

v3-commands.html.md.erb
Please do not pull this in yet, thank you.
This command no longer exist with 6.38.0; it has been integrated into `cf app`.
=> Remove V3-APP From List of Experimental

services/_using-vol-services.html.md.erb
This docs update reflects upcoming changes in `nfs-volume-release`.  We are promoting the existing `nfs-experimental` service from "experimental" to "production" and deprecating the original fuse-based nfs service to `nfs-legacy`.
This PR is dependent on the [next release](https://github.com/cloudfoundry/nfs-volume-release/releases) of `nfs-volume-release` to 1.5.4.
[#160406301](https://www.pivotaltracker.com/story/show/160406301)
Signed-off-by: Paul Warren <paul.warren@emc.com>
@julian-hj @mariash @webdave
=> NFS Volumes Update

services/_using-vol-services.html.md.erb
We added a section on how to use SMB shares in `Using Volume Services` guide.
[#160595591](https://www.pivotaltracker.com/story/show/160595591)
Maria & @davewalter
=> Add SMB volume service to using volume services guide

services/sharing-instances.html.md.erb
Some of our CF end users were trying to share their instances. They googled for `cf instance sharing` and ended up on https://docs.cloudfoundry.org/devguide/services/sharing-instances.html
So far so good, but the first command that's written there is `cf enable-feature-flag service_instance_sharing` - if they run that, they fail, since it's meant to be run by the platform operator. This PR clarifies that, so that our end users ignore the first command and continue with the end user docs.
=> highlight that instance sharing needs to be enabled by platform ops

deploy-apps/stacks.html.md.erb
Document section “Restaging Applications on a New Stack” needs updates for 2.4.0:
- The command output for “Step 1) Use the cf stack command… “ should be updated to include both stacks released with 2.4.0 (i.e. cflinuxfs2 and cflinuxfs3)
- Step (2) is not accurate, since `cf push` commands will NOT change the stack of an existing app. 
That step should say instead:
"To change your stack and restage your application, use the `cf push` command. For example, to restage your app on the cflinusfs3 stack cflinuxfs2 you can run `cf push MY-APP -s cflinuxfs3`:”  
The corresponding command output screenshot should also be updated accordingly.
=> Update "Changing Stacks" with cflinuxfs3 reference

deploy-apps/routes-domains.html.md.erb
Update docs for SD internal cli feature:
- Added cli command in Internal Domain section
- Moved map-route details to Internal Routes section
https://docs.cloudfoundry.org/devguide/deploy-apps/routes-domains.html
See #161940347
=> Update for SD internal cli feature

deploy-apps/push-docker.html.md.erb
provided explicit recommendations to use tags and explain the consequences of not doing so
=> clarify docker app tag behavior

deploy-apps/routes-domains.html.md.erb
Service discovery is no longer experimental so we can remove these notes.
/cc @ameowlia
=> Remove experimental note for internal routes in Routes and Domains page

deploy-apps/blue-green.html.md.erb
Remove Autopilot since it is not maintained anymore. Its repository is in a read-only mode.
=> Remove unmaintained Autopilot from impl. section

services/_using-vol-services.html.md.erb
- nfs-legacy is now identical to nfs
[#159782234](https://www.pivotaltracker.com/story/show/159782234)
Co-authored-by: Dave Walter <dwalter@pivotal.io>
@davewalter @julian-hj
=> Update volume services doc for upcoming v2.0.0 changes

services/managing-services.html.md.erb
We recently finished the multi-service registration feature, that adds a -b flag to service related commands, to filter the service by broker name when there are multiple services with the same name.
This PR updates documentation for those commands.
More info [here](https://www.pivotaltracker.com/story/show/158422603).
=> Update docs to reflect multi service registration

services/managing-services.html.md.erb
The command `create-service` have notes that use the term service instance which is not correct in the context since it refers to services
More information on the [tracker story](https://www.pivotaltracker.com/story/show/165760197)
Best Regards,
Niki
On behalf of SAPI Team
=> Fix improper wording in managing-services docs 

deploy-apps/_c2c_oss_overlay.html.md.erb
The number of cells that can be supported with a overlay subnet mask
of /20 is 15 cells.
The calculation for this is 2^(24-20) for 16 total, with one reserved
subnet for the single-ip-only range.
=> c2c overlay overlay configuration corrected

deploy-apps/manifest-attributes.html.md.erb
[The `buildpack:` attribute is deprecated.](https://docs.cloudfoundry.org/devguide/deploy-apps/manifest-attributes.html#buildpack)
=> buildpack -> buildpacks

deploy-apps/manifest-attributes.html.md.erb
I noticed this link was broken in the docs. The section was moved to the cf cli docs in [a commit a few months ago](https://github.com/cloudfoundry/docs-cf-cli/commit/6ad68cc550edc8be745b60dfbc2e19cd4cb0e611\#diff-c06c40a24f88e96bae204d1df4014664) but the link was not updated to reflect this.
=> Fix find-app link in app manifest topic

deploy-apps/rolling-deploy.html.md.erb
I've noticed confusion from end users around the production-readiness of the `cf v3-zdt-push` command. This PR updates the styling of several of the notes in the "Rolling App Deployments" documentation to make it more noticeable that this command is **experimental** and intended for use by early-adopters for testing.
A proper version of this functionality is currently being added to the V7 CLI by the CAPI and VAT teams. See the [Rolling Deployments Epic](https://www.pivotaltracker.com/story/show/163206256) of stories for more information.
=> Make warnings more noticeable for "Rolling App Deployments"

deploy-apps/manifest-attributes.html.md.erb
Hello Documentation Friends!
We were working on a [story](https://www.pivotaltracker.com/story/show/166249597) to fix a URL in our `cf push` output, when we noticed that the documentation regarding the deprecated top-level attributes didn't have parallel language to our output.
This pull request is meant to resolve that.
In this pull request, we've used standard double quotes, but there are other points in the document that appear to have 'smart' quotes. 
CC @acrmp
=> Match CLI's warning on top-level attribute deprecation.

deploy-apps/deploy-app.html.md.erb
The existing language confused a colleague of mine into thinking that .profile was a staging-time thing. [It's not...](https://github.com/cloudfoundry/buildpackapplifecycle/blob/master/launcher/launcher_unix.go#L25-L27) This change will hopefully avoid that confusion for others. It also suggests an example that could only make sense at app-start time.
=> Be explicit on when .profile gets run, and give an example

deploy-apps/environment-variable.html.md.erb
The next capi-release (`1.83.0`) will include the organization GUID and organization name for an
app in its VCAP_APPLICATION environment variables.
**See:**
https://github.com/cloudfoundry/cloud_controller_ng/commit/0f9ecb75a1081d64f84d1f3607cbf2050d1a38b1
**CAPI Story:**
[#166547310](https://www.pivotaltracker.com/story/show/166547310)
Co-authored-by: Tim Downey <tdowney@pivotal.io>
Co-authored-by: Mona Mohebbi <mmohebbi@pivotal.io>
=> Document organization guid and name in VCAP_APPLICATION env vars

services/managing-services.html.md.erb
This adds documentation for the new --upgrade behaviour, that allows developers to upgrade individual service instances. It also indicates how to see that an upgrade is available.
I changed some documentation relating to "upgrading" plans to bring it in line with the new docs and to make more sense
Note: I accidentally pushed to origin/master and then reverted, I didn't realise I had commit rights - very sorry.
=> Add upgrade flag to service instance update docs

services/fluentd.html.md.erb
The current link gets you to Page Not Found page.
With this fix, you get to the correct page.
=> Fix the expired link for Fluentd Configuration File

deploy-apps/_disable_network_policy_enforcement_oss.html.md.erb
`disable_container_network_policy` needs to be set to true to disable Disable Network Policy Enforcement
See https://bosh.io/jobs/vxlan-policy-agent?source=github.com/cloudfoundry/silk-release&version=2.24.0#p%3ddisable_container_network_policy
> disable_container_network_policy¶
>WARNING!!! Disables network policy enforcement. Setting this property to true allows all app containers to access any other app container with no restrictions.
>Default: false
=> Fix _disable_network_policy_enforcement_oss.html.md.erb typo

multiple-processes.html.md.erb
As per the v3-app commands page, the step
`$ cf v3-app myapp` needs to be changed to `$ cf app myapp`
Issue Raised: https://github.com/cloudfoundry/docs-dev-guide/issues/372
=> Updated documentation to change v3-app, Issue: #372

custom-ports.html.md.erb
The steps here don't work if you are trying to remove an app port. You also need to delete the route-mapping before you can remove it from the app.
Let me know if you want all the steps written out too.
=> Add a note about deleting app ports

custom-ports.html.md.erb
**Motivation:**
The original step-3: `cf curl /v2/routes?q=host:HOST-NAME` is not able to list TCP routes.
**Modification in this PR:**
I added `cf curl /v2/apps/APP-GUID/routes` to step-3, which will be able to list all routes of an app.
-- Weien Chen (wchen@pivotal.io)
=> Improve the steps, to be compatible with TCP routes.

deploy-apps/routes-domains.html.md.erb
- when no instance is found now returns a 400 
- used to return a 404
=> Update surgical routing docs

deploy-apps/environment-variable.html.md.erb
Fixing "To see the value of the VCAP\_SERVICES" to "To see the value of the VCAP_SERVICES"
=> Fixing rendering typo

egress-policies.html.md.erb
This PR clarifies that the egress policy feature only works on Linux based Diego Cells and not Windows based Diego Cells.
=> Clarify that egress policies only works on Linux not windows

deploy-apps/cf-networking.html.md.erb
As a result of an interrupt we received, we realized there is no
documentation around the default value of 50 polices for space
developers.
[#172150410](https://www.pivotaltracker.com/story/show/172150410)
Co-authored-by: Christian Ang <angc@vmware.com>
=> Add section for network policy quotas

services/_using-vol-services.html.md.erb
Hi Folks, 
We recently added a new cache flag that we would like to document.  
Note: For TAS, this change can be back-ported to 2.7 onwards. Let us know if you'd like us to submit separate PRs for those versions.
[#172510710](https://www.pivotaltracker.com/story/show/172510710)
Authored-by: Paul Warren <pwarren@pivotal.io>
=> Document the new cache flag

deploy-apps/_v3-note.html.md.erb, deploy-apps/manifest-attributes.html.md.erb, deploy-apps/rolling-deploy.html.md.erb, deploy-apps/routes-domains.html.md.erb, multiple-processes.html.md.erb, push-sub-commands.html.md.erb, push.html.md.erb, sidecars.html.md.erb
Hi Docs Team. We are preparing to GA cf CLI version 7. We are trying to remove references to any beta tags left behind. This is one of 3 PRs. The others should be in docs-cf-cli, docs-cf-admin.
=> Update docs in preparation for cli V7 GA

custom-ports.html.md.erb, deploy-apps/blue-green.html.md.erb, deploy-apps/cf-networking.html.md.erb, deploy-apps/routes-domains.html.md.erb, deploy-apps/troubleshoot-app-health.html.md.erb, egress-policies.html.md.erb, routing-index.html.md.erb, services/route-binding.html.md.erb
Replaces:
- Routing
- Container-to-Container Networking
- CF Networking
[#174581818](https://www.pivotaltracker.com/story/show/174581818)
This change should also be backported all the way back to TAS `2.7` 
- https://github.com/cloudfoundry/docs-dev-guide/pull/410
- https://github.com/cloudfoundry/docs-cf-admin/pull/189
- https://github.com/cloudfoundry/docs-cloudfoundry-concepts/pull/146
- https://github.com/pivotal-cf/docs-operating-pas/pull/38
- https://github.com/pivotal-cf/docs-ops-manager/pull/93
- https://github.com/pivotal-cf/docs-pcf-security/pull/116
=> Update owner: CF for VMs Networking

deploy-apps/large-app-deploy.html.md.erb
Starting the staging container fails when exceeding the env var limit e.g. by binding too many services.
See https://github.com/cloudfoundry/garden-runc-release/issues/160
=> Document env var limits for apps

sidecars.html.md.erb
To deploy the  config server derived from `capi-sidecar-samples`, we need to copy the binary to the app directory to deploy as a sidecar.
=> Need to copy the config server binary

services/oms-nozzle.html.md.erb
* The nozzle is no longer in beta
* Remove the `--skip-ssl-validation` flags as we don't want to be recommending these
* Update the Github repository location in the instructions to refer to the new location
CC @njbennett
Thanks!
=> Update Azure Nozzle Docs

services/oms-nozzle.html.md.erb
* The nozzle is no longer in beta
* Remove the `--skip-ssl-validation` flags as we don't want to be recommending these
* Update the Github repository location in the instructions to refer to the new location
CC @njbennett
Thanks!
=> Update Azure Nozzle Docs (12.42)

services/oms-nozzle.html.md.erb
* The nozzle is no longer in beta
* Remove the `--skip-ssl-validation` flags as we don't want to be recommending these
* Update the Github repository location in the instructions to refer to the new location
CC @njbennett
Thanks!
=> Update Azure Nozzle Docs (12.21)

services/oms-nozzle.html.md.erb
* The nozzle is no longer in beta
* Remove the `--skip-ssl-validation` flags as we don't want to be recommending these
* Update the Github repository location in the instructions to refer to the new location
CC @njbennett
Thanks!
=> Update Azure Nozzle Docs (12.0)

deploy-apps/environment-variable.html.md.erb
New VCAP_SERVICE attributes `binding_guid` and `instance_guid` have been added in [cloud_controller](https://github.com/cloudfoundry/cloud_controller_ng/pull/2030) 
Also documented `syslog_drain_url` and `volume_mounts` since they were missing.
=> Document new attributes to VCAP_SERVICE

revisions.html.md.erb
There has been some confusion recently because the revisions APIs are experimental, but there isn't any mention in the docs.
Example: https://github.com/cloudfoundry/cloud_controller_ng/issues/2044
=> Add note that revisions are experimental

services/application-binding.html.md.erb
The current documentation about [Update Service Credentials](https://docs.cloudfoundry.org/devguide/services/application-binding.html#update-credentials) require
a downtime. Service credentials could be updated without a downtime also.
This commit adds a new section to the [Update Service Credentials](https://docs.cloudfoundry.org/devguide/services/application-binding.html#update-credentials), which describes how to update
service binding credentials without a downtime.
Fixes issue #426
=> Add a new section to "Update Service Credentials" without downtime

services/oms-nozzle.html.md.erb
instead of switching to creating the user with the cf cli 1/2 through, we continue to use the uaac to create the user and then assign rights.
=> create user using uaac instead of cf

deploy-apps/ssh-apps.html.md.erb
There is an unintentional double backtick here. This can be seen in the published documentation e.g.
=> Remove stray backtick

deploy-apps/push-docker.html.md.erb
A change of the credentials used to push a docker based application
requires a re-push of the application with the new credentials.
Ohterwise CF wan't be able to start this application because during start access
to the container registry is required. A start could be triggered
because of different reasons (an appliation crash or application evacuation, etc.).
=> Adds a note for private container credentials change and rotation

http2-protocol.html.md.erb, index.html.md.erb, routing-index.html.md.erb
Related PRs:
- Admin Guide: https://github.com/cloudfoundry/docs-cf-admin/pull/207
- Nav: https://github.com/cloudfoundry/docs-book-cloudfoundry/pull/112
Root Issue: cloudfoundry/routing-release#200
=> Add HTTP/2 Documentation for App Developers

deploy-apps/manifest-attributes.html.md.erb
Hello. These docs are for the ongoing HTTP/2 feature: cloudfoundry/routing-release#200
=> Add docs for protocol in routes attributes for manifest

deploy-apps/rolling-deploy.html.md.erb
There are limitations with the scale and update V3 APIs during a rolling deploy. This pr adds those limitations
to the [rolling deploy](https://docs.cloudfoundry.org/devguide/deploy-apps/rolling-deploy.html) docs. The limitations are described in the issue #442.
fixes #442
=> Add rolling deploy limitations for the V3 APIs

capi/client-libraries.html.md.erb
- Standardize format for links to external client libraries
- Remove links to abandoned client library projects
- Reorder python libraries to promote cloudfoundry-community repos first
=> update client library references

deploy-apps/manifest-attributes.html.md.erb
In cf cli manifest https://docs.cloudfoundry.org/devguide/deploy-apps/healthchecks.html#health_check_timeout only mentions the two keys below
yaml
```
health-check-type: http
health-check-http-endpoint: /actuator/health
```
See https://www.pivotaltracker.com/n/projects/966314/stories/157646582
and https://github.com/cloudfoundry/cloud_controller_ng/commit/555097091f8cea8285eb8d6c8da9c7a396f76a0f
The following manifest keys ...
```yaml
timeout: 180
health-check-type: http
health-check-http-endpoint: /actuator/health
health-check-timeout: 31
health-check-invocation-timeout: 30
```
... result in the following output with capi-release 1.111.0
```
$ cf get-health-check osb-cmdb-broker-0
[...]
process   health check   endpoint (for http)   invocation timeout
web       http …
```
=> Add health-check-invocation-timeout to manifest doc

services/log-management.html.md.erb
Due to changes in Go 1.17, components involved in the streaming app logs workflow will no longer be able to parse IPs with leading zeros.
Examples of IPs with leading zeros:
* 10.0.01.14
* 010.0.1.14
* 10.0.1.014
All of the above examples should be entered as 10.0.1.14 for them to be parsed correctly.
=> Add a note to not use IPs with leading zeros

services/log-management.html.md.erb
Deprecating cf-drain-cli plugin in favor of the generic CLI commands.
cc @mkocher
=> Remove references to cf-drain-cli plugin

services/fluentd.html.md.erb
- update frame_type to handle app logs correctly
- remove udp, has never been supported with syslog agents
- added parsing for rfc5424
- changed port to 8080 to better represent the common usecase of cf pushed fluentd
- added note about tcp routing
=> update fluentd docs to be correct

deploy-apps/environment-variable.html.md.erb, deploy-apps/manifest-attributes.html.md.erb
Add a note to use user-provided service instances instead.
User-provided env vars show up in cf cli (manifest diff) and CC logs.
Removed the sentence to use manifest  variables to hide
security sensitive values. They are printed by cf cli v8 (manifest diff) and
the only real use case would be env vars.
=> Do not use env vars for credentials

http2-protocol.html.md.erb
Add a list of sample HTTP/2 and gRPC applications to the HTTP/2 application developer docs. This was partially inspired because getting HTTP/2 working on CF can be a bit tricky for some languages/frameworks (looking at you ASP.NET 😠).
=> Add sample HTTP/2 and gRPC applications

services/log-management.html.md.erb
Hello everyone,
with this PR, I've added the documentation of the mTLS feature of the Syslog drain functionality rolled out inside the Cloud Controller [here](https://github.com/cloudfoundry/cloud_controller_ng/pull/3028) and inside the Loggreagator Agent Release [here](https://github.com/cloudfoundry/loggregator-agent-release/pull/119). 
The corresponding PR describes, how to inject the corresponding certs inside the user-provided service and establish a Syslog connection over mTLS.
The corresponding part for the Loggregator Release is currently in state `under review`, but we've already prepared the Community documentation for the usage of the feature.
=> Add the mTLS syslog drain feature to the documentation

deploy-apps/deploy-app.html.md.erb
- `ustomize` -> `Customize`
- remove redundant `with`
=> docs: fix phrasing & spelling in `deploy-apps/deploy-app`

deploy-apps/manifest-attributes.html.md.erb
Updated docs to specify the default log rate limit, which is 16k.
Fixed the attribute name from log-rate-limit to be log-rate-limit-per-second
=> Fix default log rate limit and attribute name

services/user-provided.html.md.erb
- bindings without ports will not work
- now suggest tls by default
=> Update cups example for syslog address.

deploy-apps/manifest-attributes.html.md.erb
* default value noted
* wrong reference to `timeout` removed (a related, but different timeout)
===
I'm 90% sure these fixes are indeed fixes, and I'm submitting this PR in part to get some validation that my understanding is indeed correct.
* the default value was deduced from error messages in my running cells, i.e. `Instance became unhealthy: Failed to make HTTP request to '/healthcheck' on port 8080: timed out after 1.00 seconds`
* I'm reasonably sure that the typo-fix is indeed a fix, but I cannot look into the head of the person that originally wrote this down.
=> 2 fixes for health-check-invocation-timeout

deploy-apps/streaming-logs.html.md.erb
Remove mention of deprecated global log rate limit.
=> Fix: streaming-logs documentation

deploy-apps/streaming-logs.html.md.erb, services/log-management.html.md.erb
- Add documentation for configuring syslog drains to forward container metrics
- Remove old deprecated documentation
=> Container metrics forwarding with syslog drains

services/_using-vol-services.html.md.erb
Re-iterates that using mapfs has performance implications. Highlights that there are other options, such as NFS export options. But we don't want to get into the game of documenting NFS, so we mention the possibility without providing details or links.
=> Highlight the performance implications of mapfs

services/_using-vol-services.html.md.erb
We think the example is guiding users to specify the uid/gid even when not needed.
- also removed NFS options all_squash because this is rarely needed
- also removed note about uid=0 because this has been the behavior since 2019 and we don't need to call out the change any more
=> Give an example of binding without uid/gid

services/log-management.html.md.erb
I've adjusted the documentation and added a general note related to the key policies `Extended Key Usage` extension inside the syslog drain case.
=> docs: Adjust the documentation and add the key policies note

deploy-apps/healthchecks.html.md.erb, deploy-apps/manifest-attributes.html.md.erb
Oops! We published https://github.com/cloudfoundry/docs-dev-guide/pull/483 too soon! Revert until the code is released.
=> Revert "Document new app readiness health checks"

deploy-apps/healthchecks.html.md.erb, deploy-apps/manifest-attributes.html.md.erb
This feature is now available in [cf-d 32.2.0](https://github.com/cloudfoundry/cf-deployment/releases/tag/v32.2.0)!
=> Revert "Revert "Document new app readiness health checks""

deploy-apps/routes-domains.html.md.erb
Formatting is currently partly broken on this page, I assume due to this missing tag...
=> Add missing tag

deploy-apps/push-docker.html.md.erb
With this [PR](https://github.com/cloudfoundry/cloud_controller_ng/pull/3467) you do not have to push your app for updating docker credentials, you can also update the latest package and restage your app.
=> Adapt update docker credentials part

deploy-apps/cf-networking.html.md.erb
This new TAS property is for TAS 6.0 only.
@anita-flegg - please let me know if this update matches your style guidelines. I wasn't sure about the if/else-ing or what branch to put it on for TAS 6.0 and open source only.
🙏 Thanks!
=> update cf-networking docs to include c2c policy limit configuration options

deploy-apps/routes-domains.html.md.erb
- The routing tier / gorouter will not always make load balancing determinations using `round-robin`, and instead will use whatever is configured on gorouter. It's worth noting that round-robin IS the default though.
- Changed along with the other changes to AZ-local routing. See: https://github.com/cloudfoundry/docs-cloudfoundry-concepts/pull/194
[#186117321](https://www.pivotaltracker.com/story/show/186117321)
=> Make reference to balancing algorithm generic

services/_using-vol-services.html.md.erb
Our docs say that `3.0` is a valid nfs version. It turns out that this was undefined behavior in old versions of nfs-utils and will not work when the underlying CF Deployments runs on Jammy (as opposed to Xenial).
Users have pointed reported:
after updating the CF deployment from a xenial to a jammy stemcell, previously working volume services ( created with `version: 3.0`) stopped working. After updating their services to use `version: 3` keeping the rest of the configuration identical, the mounts succeeded again.
The best proof for this change (without trying to track a commit in nfs-utils source), I could find is a comment by Steve Dickson (the maintainer) here: https://bugzilla.redhat.com/show_bug.cgi?id=1522633
```
There are no minor versions with NFS v3
```
=> fix error for supported nfs versions

deploy-apps/environment-variable.html.md.erb, deploy-apps/large-app-deploy.html.md.erb
With cflinuxfs4 (Ubunut 22.04) the 130k limit for env vars is per env var and not anymore for all env vars.
=> Update CF env var size limit

deploy-apps/environment-variable.html.md.erb
- <code> tags instead of markdown backticks
=> Fix formatting within html note

services/log-management.html.md.erb
- It is not possible to define an aggregate syslog drain using cf create-user-provided-service. Aggregate drains are defined at deployment time.
- I think this content was added due to some confusion between metrics emitted against syslog drains vs their configuration in #491.
=> Remove guidance to set drain_scope drain parameter

services/log-management.html.md.erb
- Backport of #503.
- It is not possible to define an aggregate syslog drain using cf create-user-provided-service. Aggregate drains are defined at deployment time.
- I think this content was added due to some confusion between metrics emitted against syslog drains vs their configuration in #491.
(cherry picked from commit 0d12e93e9347c990f9e1d95b672fa26be40f53bb)
=> Remove guidance to set drain_scope drain parameter (backport)

deploy-apps/push-docker.html.md.erb
When Cloud Foundry runs a "Docker app", it bases the app on the filesystem and metadata in a Docker container image, but it runs the app instances as Garden containers, not as containers managed by the Docker container engine.
Also replace irrelevant link to `docker start` documentation with direct references to the directives providing the default start command for an app based on a Docker image.
=> Clarify references to Docker images when pushing apps

services/user-provided.html.md.erb
- The PR adds a note about the usage of RFC-5424 on HTTP/ HTTPS and RFC-6587 on TCP connections.
**Result:**
=> docs: Adjust the syslog drain docs

revisions.html.md.erb
Mirrors the changes in https://github.com/cloudfoundry/cloud_controller_ng/pull/3920, if they get merged.
=> Update revisions to correct that they are not created for tasks or not running apps

deploy-apps/canary-deploy.html.md.erb, deploy-apps/rolling-deploy.html.md.erb
This should be backported to any TAS versions with either of these files. Rolling deployments pre-dates canary, so it maybe the case you need to split this commit.
=> Add new/stopped app limitation for deployments

deploy-apps/canary-deploy.html.md.erb, deploy-apps/rolling-deploy.html.md.erb
PR applies to TAS 7 immediately.
And for TAS 4/5/6 in the next patch release that contains at least CLI version `v8.7.12` or cli bosh release `v1.66.0`
=> Document max_in_flight for deployments

services/_using-vol-services.html.md.erb
As of [smb-volume-release v.3.2.0](https://github.com/cloudfoundry/smb-volume-release/releases/tag/v3.2.0), we support smb 3.1.1 protocol version with Jammy stemcells.
Additionally, use pora from cf-acceptance-tests since that asset is maintained more regularly
=> Update docs for SMB 3.1.1 support

deploy-apps/deploy-app.html.md.erb
- Add links to newer push features that have docs pages but are not linked from the main "cf push" page
=> Update deploy app (push) docs with new links

custom-per-route-options.html.md.erb, deploy-apps/manifest-attributes.html.md.erb
This is a fix for https://github.com/cloudfoundry/cloud_controller_ng/issues/4198.
=>  fix: Rename least-connection load-balancing algorithm consistently

custom-per-route-options.html.md.erb
Documentation adjustments for 
https://github.com/cloudfoundry/cli/pull/3372
https://github.com/cloudfoundry/cli/pull/3366
=> Per-route options via CF cli

services/log-management.html.md.erb
We get customer tickets where customers ask for help when configuring their syslog drains. 
In my team we planned to enhance the documentation with a section about the protocols, certificates and some hints for troubleshooting common problems with syslog drains.
=> add section for syslog-drain-url protocols, certificates and troubleshooting hints

deploy-apps/manifest-attributes.html.md.erb
When working with the [DataDog buildpack](https://github.com/DataDog/datadog-cloudfoundry-buildpack/pull/198) I realized that using a .zip file is not documented. This addresses that shortcoming.
=> Use a .zip file for a buildpack

deploy-apps/rolling-deploy.html.md.erb
The note is kind of duplicate in there but still I have the feeling people that only check for the canary option might not see the note in the cancel deployment section and therefore are not aware that cancel a deployment (especially after 100% of instances got replaced) might result in a downtime of the app.
=> [deploy-apps] Add warning note to step-weight example
